build site:
  only:
    - merge_requests
  image: node:latest
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - ./build

unit test:
  image: node:latest
  stage: test
  script:
    - npm install --progress=false
    - npm run test

  only:
    - merge_requests

cache:
  paths:
    - node_modules/

deploy:
  only:
    - merge_requests
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh pettegre@it2810-40.idi.ntnu.no 'sudo systemctl stop express.service; sudo rm -rf /var/www/server/prosjekt3'
    - rsync -rav --delete build/* pettegre@it2810-40.idi.ntnu.no:/var/www/server/prosjekt3/
    - rsync -rav /builds/IT2810-H19/teams/team-40/project-3-backend/node_modules pettegre@it2810-40.idi.ntnu.no:/var/www/server/prosjekt3/
    - rsync -rav /builds/IT2810-H19/teams/team-40/project-3-backend/package.json pettegre@it2810-40.idi.ntnu.no:/var/www/server/prosjekt3/
    - rsync -rav /builds/IT2810-H19/teams/team-40/project-3-backend/package-lock.json pettegre@it2810-40.idi.ntnu.no:/var/www/server/prosjekt3/
    - ssh pettegre@it2810-40.idi.ntnu.no 'cd /var/www/server/prosjekt3; npm install; sudo chmod +x server.js; sudo systemctl start express.service'